# Generated by Django 4.2.6 on 2023-10-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rental_price_month',
            new_name='monthly_rental_price',
        ),
    ]
