# Generated by Django 4.2.6 on 2023-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_rental_price_month_book_monthly_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('rented', 'rented'), ('sold', 'sold')], max_length=50),
        ),
    ]
