# Generated by Django 4.2.6 on 2023-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
